# Generated by Django 6.0.1 on 2026-01-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='key',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
